services:
   app:
     image: shelajev/personal-assistant-gemini:1.0-SNAPSHOT
     ports:
       - 3000:3000
     env_file:
       - .env
     environment:
       - QUARKUS_HTTP_HOST=localhost
       - GDRIVEMCP_AUTH_API_URL=http://localhost:8001/
       - GDRIVEMCP_URL=http://mcp-gdrive-sse:8000/sse
   mcp-gdrive-sse:
    image: olegselajev241/mcp-gdrive-sse:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}